version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    tty: true
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    networks:
      - node-network  
    depends_on:
      - node
    
  node:
    build:
      context: node
    container_name: node
    tty: true
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    networks:
      - node-network
    depends_on: 
      - db  

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0    
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge